version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # Configurações de rede que resolvem o erro de interface que você teve
    network_mode: "host" 
    restart: unless-stopped

  netdata:
    container_name: netdata
    image: netdata/netdata:latest
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
